version: "1.0"

services:
  postgres:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/
    env_file:
      - ".env.docker"
    networks:
      - api-network

  api:
    build: .
    command: bash -c "alembic upgrade head && python src/app.py run -h 0.0.0.0"
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file:
      - ".env"
    depends_on:
      - postgres
    networks:
      - api-network

volumes:
  postgres_data:

networks:
  api-network:
    driver: bridge