"""create tables

Revision ID: 467268d35b6b
Revises: 473cc01beee2
Create Date: 2023-03-13 19:45:57.515151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "467268d35b6b"
down_revision = "473cc01beee2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alibaba_source",
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("min_price", sa.String(), nullable=True),
        sa.Column("max_price", sa.String(), nullable=True),
        sa.Column("rrp_price", sa.String(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "similarity",
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "amazon_source",
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("min_price", sa.String(), nullable=True),
        sa.Column("max_price", sa.String(), nullable=True),
        sa.Column("rrp_price", sa.String(), nullable=True),
        sa.Column("alibaba_source_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alibaba_source_id"], ["alibaba_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "most_similar",
        sa.Column("amazon_source_id", sa.UUID(), nullable=True),
        sa.Column("alibaba_source_id", sa.UUID(), nullable=True),
        sa.Column("similarity", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alibaba_source_id"], ["alibaba_source.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["amazon_source_id"], ["amazon_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "urls",
        sa.Column("link", sa.String(), nullable=True),
        sa.Column("alibaba_product_id", sa.UUID(), nullable=True),
        sa.Column("amazon_product_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alibaba_product_id"], ["alibaba_source.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["amazon_product_id"], ["amazon_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "videos",
        sa.Column("videos", sa.String(), nullable=True),
        sa.Column("alibaba_product_id", sa.UUID(), nullable=True),
        sa.Column("amazon_product_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alibaba_product_id"], ["alibaba_source.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["amazon_product_id"], ["amazon_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("videos")
    op.drop_table("urls")
    op.drop_table("most_similar")
    op.drop_table("amazon_source")
    op.drop_table("similarity")
    op.drop_table("alibaba_source")
    # ### end Alembic commands ###
