"""First commit

Revision ID: 473cc01beee2
Revises: 
Create Date: 2023-03-12 11:43:44.147868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "473cc01beee2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
