"""change

Revision ID: 594f890babd7
Revises: 473cc01beee2
Create Date: 2023-03-12 14:53:59.729400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "594f890babd7"
down_revision = "473cc01beee2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "amazon_source_alibaba_source_id_fkey", "amazon_source", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "amazon_source",
        "alibaba_source",
        ["alibaba_source_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "most_similar_amazon_source_id_fkey", "most_similar", type_="foreignkey"
    )
    op.drop_constraint(
        "most_similar_alibaba_source_id_fkey", "most_similar", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "most_similar",
        "amazon_source",
        ["amazon_source_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "most_similar",
        "alibaba_source",
        ["alibaba_source_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("urls_alibaba_product_id_fkey", "urls", type_="foreignkey")
    op.drop_constraint("urls_amazon_product_id_fkey", "urls", type_="foreignkey")
    op.create_foreign_key(
        None,
        "urls",
        "alibaba_source",
        ["alibaba_product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None, "urls", "amazon_source", ["amazon_product_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("videos_amazon_product_id_fkey", "videos", type_="foreignkey")
    op.drop_constraint("videos_alibaba_product_id_fkey", "videos", type_="foreignkey")
    op.create_foreign_key(
        None,
        "videos",
        "amazon_source",
        ["amazon_product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "videos",
        "alibaba_source",
        ["alibaba_product_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.drop_constraint(None, "videos", type_="foreignkey")
    op.create_foreign_key(
        "videos_alibaba_product_id_fkey",
        "videos",
        "alibaba_source",
        ["alibaba_product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "videos_amazon_product_id_fkey",
        "videos",
        "amazon_source",
        ["amazon_product_id"],
        ["id"],
    )
    op.drop_constraint(None, "urls", type_="foreignkey")
    op.drop_constraint(None, "urls", type_="foreignkey")
    op.create_foreign_key(
        "urls_amazon_product_id_fkey",
        "urls",
        "amazon_source",
        ["amazon_product_id"],
        ["id"],
    )
    op.create_foreign_key(
        "urls_alibaba_product_id_fkey",
        "urls",
        "alibaba_source",
        ["alibaba_product_id"],
        ["id"],
    )
    op.drop_constraint(None, "most_similar", type_="foreignkey")
    op.drop_constraint(None, "most_similar", type_="foreignkey")
    op.create_foreign_key(
        "most_similar_alibaba_source_id_fkey",
        "most_similar",
        "alibaba_source",
        ["alibaba_source_id"],
        ["id"],
    )
    op.create_foreign_key(
        "most_similar_amazon_source_id_fkey",
        "most_similar",
        "amazon_source",
        ["amazon_source_id"],
        ["id"],
    )
    op.drop_constraint(None, "amazon_source", type_="foreignkey")
    op.create_foreign_key(
        "amazon_source_alibaba_source_id_fkey",
        "amazon_source",
        "alibaba_source",
        ["alibaba_source_id"],
        ["id"],
    )
    # ### end Alembic commands ###
