"""change

Revision ID: 5ac10c3f6d45
Revises: 594f890babd7
Create Date: 2023-03-12 17:12:17.915503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ac10c3f6d45"
down_revision = "594f890babd7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("alibaba_source", sa.Column("min_price", sa.String(), nullable=True))
    op.add_column("alibaba_source", sa.Column("max_price", sa.String(), nullable=True))
    op.drop_column("alibaba_source", "price")
    op.add_column("amazon_source", sa.Column("min_price", sa.String(), nullable=True))
    op.add_column("amazon_source", sa.Column("max_price", sa.String(), nullable=True))
    op.drop_column("amazon_source", "price")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "amazon_source",
        sa.Column("price", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("amazon_source", "max_price")
    op.drop_column("amazon_source", "min_price")
    op.add_column(
        "alibaba_source",
        sa.Column("price", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("alibaba_source", "max_price")
    op.drop_column("alibaba_source", "min_price")
    # ### end Alembic commands ###
