"""new tables

Revision ID: 600897653c5d
Revises: 473cc01beee2
Create Date: 2023-03-12 11:57:17.387637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600897653c5d'
down_revision = '473cc01beee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alibaba_source',
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amazon_source',
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('most_similar',
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('similarity',
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('urls',
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('urls')
    op.drop_table('similarity')
    op.drop_table('most_similar')
    op.drop_table('amazon_source')
    op.drop_table('alibaba_source')
    # ### end Alembic commands ###
