"""empty message

Revision ID: 687b54d380c4
Revises: 8859c3d03ffa
Create Date: 2023-04-25 21:39:43.210373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687b54d380c4'
down_revision = '8859c3d03ffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alibaba_product_ids', sa.Column('from_where', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alibaba_product_ids', 'from_where')
    # ### end Alembic commands ###
