"""create new table

Revision ID: 8859c3d03ffa
Revises: 97354eb4bdb5
Create Date: 2023-04-08 17:44:31.290216

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8859c3d03ffa'
down_revision = '97354eb4bdb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('average_price',
                    sa.Column('average', sa.String(), nullable=True),
                    sa.Column('amazon_product_id', sa.UUID(), nullable=True),
                    sa.Column('id', sa.UUID(), nullable=False),
                    sa.ForeignKeyConstraint(['amazon_product_id'], ['amazon_source.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('average_price')
    # ### end Alembic commands ###
