"""create new table

Revision ID: 97354eb4bdb5
Revises: bbb4c816be64
Create Date: 2023-03-22 20:08:43.108247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "97354eb4bdb5"
down_revision = "bbb4c816be64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alibaba_product_ids",
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("alibaba_product_id", sa.UUID(), nullable=True),
        sa.Column("amazon_product_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alibaba_product_id"], ["alibaba_source.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["amazon_product_id"], ["amazon_source.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("amazon_product_ids")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "amazon_product_ids",
        sa.Column("product_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("alibaba_product_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("amazon_product_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["alibaba_product_id"],
            ["alibaba_source.id"],
            name="amazon_product_ids_alibaba_product_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["amazon_product_id"],
            ["amazon_source.id"],
            name="amazon_product_ids_amazon_product_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="amazon_product_ids_pkey"),
    )
    op.drop_table("alibaba_product_ids")
    # ### end Alembic commands ###
