"""create new table

Revision ID: bbb4c816be64
Revises: 467268d35b6b
Create Date: 2023-03-18 14:00:20.607199

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbb4c816be64'
down_revision = '467268d35b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_keywords',
    sa.Column('amazon_source_id', sa.UUID(), nullable=True),
    sa.Column('alibaba_source_id', sa.UUID(), nullable=True),
    sa.Column('list_of_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['alibaba_source_id'], ['alibaba_source.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['amazon_source_id'], ['amazon_source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_keywords')
    # ### end Alembic commands ###
