"""change uuid

Revision ID: e8c2a1329e15
Revises: aa1512465a7a
Create Date: 2023-03-12 12:43:36.511342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c2a1329e15'
down_revision = 'aa1512465a7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alibaba_source', sa.Column('images_id', sa.UUID(), nullable=False))
    op.add_column('alibaba_source', sa.Column('amazon_source_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'alibaba_source', 'urls', ['images_id'], ['id'])
    op.create_foreign_key(None, 'alibaba_source', 'amazon_source', ['amazon_source_id'], ['id'])
    op.add_column('amazon_source', sa.Column('images_id', sa.UUID(), nullable=False))
    op.add_column('amazon_source', sa.Column('alibaba_source_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'amazon_source', 'alibaba_source', ['alibaba_source_id'], ['id'])
    op.create_foreign_key(None, 'amazon_source', 'urls', ['images_id'], ['id'])
    op.add_column('most_similar', sa.Column('amazon_source_id', sa.UUID(), nullable=False))
    op.add_column('most_similar', sa.Column('alibaba_source_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'most_similar', 'amazon_source', ['amazon_source_id'], ['id'])
    op.create_foreign_key(None, 'most_similar', 'alibaba_source', ['alibaba_source_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'most_similar', type_='foreignkey')
    op.drop_constraint(None, 'most_similar', type_='foreignkey')
    op.drop_column('most_similar', 'alibaba_source_id')
    op.drop_column('most_similar', 'amazon_source_id')
    op.drop_constraint(None, 'amazon_source', type_='foreignkey')
    op.drop_constraint(None, 'amazon_source', type_='foreignkey')
    op.drop_column('amazon_source', 'alibaba_source_id')
    op.drop_column('amazon_source', 'images_id')
    op.drop_constraint(None, 'alibaba_source', type_='foreignkey')
    op.drop_constraint(None, 'alibaba_source', type_='foreignkey')
    op.drop_column('alibaba_source', 'amazon_source_id')
    op.drop_column('alibaba_source', 'images_id')
    # ### end Alembic commands ###
