[program:gcs_celery]
command=celery -A app.celery_app worker --config celery_config.py
directory=/var/app/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
user=webapp
redirect_stderr=true
stdout_logfile=/var/log/gcs_celery.out.log
stopwaitsecs=3600
startsecs = 0

[program:gcs_flower]
command=flower --config=flower_config.py
directory=/var/app/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=1
user=webapp
redirect_stderr=true
stdout_logfile=/var/log/gcs_flower.out.log
stopwaitsecs=3600
startsecs = 0